//
// Created by SMTEmon.
//

#include <bits/stdc++.h>

using namespace std;
using lli = long long int;

class Graph
{
public:
    lli nodeCount;
    vector<vector<pair<lli, lli>>> adj;
    Graph(lli nodeCount)
    {
        this->nodeCount = nodeCount;
        adj.resize(nodeCount);
    }

    void add_edges(lli u, lli v, lli weight)
    {
        adj[u].push_back(make_pair(weight, v));

        // undirected
        adj[v].push_back(make_pair(weight, u));
    }

    vector<lli> prims(vector<vector<pair<lli, lli>>> &adj, lli src)
    {
        lli res = 0;

        vector<lli> cost(nodeCount, INT_MAX);
        vector<bool> visited(nodeCount, false);

        priority_queue<pair<lli, lli>, vector<pair<lli, lli>>, greater<pair<lli, lli>>> pq;

        pq.push(make_pair(0, src));
        cost[src] = 0;

        while (!pq.empty())
        {
            pair<lli, lli> node = pq.top();
            lli dest = node.second;
            pq.pop();
            if (visited[dest])
                continue;
            visited[dest] = true;

            for (pair<lli, lli> nei : adj[dest])
            {

                if (cost[dest] != INT_MAX && cost[nei.second] > nei.first)
                {

                    if (!visited[nei.second])
                    {
                        cost[nei.second] = nei.first;
                        pq.push(make_pair(cost[nei.second], nei.second));
                    }
                }
            }
        }
        return cost;
    }
};

// main() generated by gemini, lazy af
int main()
{
    // Fast I/O
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);

    lli nodes, edges;
    if (cin >> nodes >> edges)
    {
        Graph g(nodes);

        for (lli i = 0; i < edges; i++)
        {
            lli u, v, w;
            cin >> u >> v >> w;
            g.add_edges(u, v, w);
        }

        lli src;
        cin >> src;

        vector<lli> cost = g.prims(g.adj, src);

        cout << "--- Prim's MST Execution Results ---\n";
        lli total_mst_weight = 0;
        bool disconnected = false;

        for (lli i = 0; i < nodes; i++)
        {
            if (cost[i] == INT_MAX)
            {
                cout << "Node " << i << ": Unreachable\n";
                disconnected = true;
            }
            else
            {
                cout << "Node " << i << " minimum edge weight to MST: " << cost[i] << "\n";
                total_mst_weight += cost[i];
            }
        }

        cout << "------------------------------------\n";
        if (disconnected)
        {
            cout << "Graph is disconnected. Total weight shown is only for the connected component.\n";
        }
        cout << "Total Minimum Spanning Tree Weight: " << total_mst_weight << "\n";
    }

    return 0;
}